id: P000450
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:40:35.298721
source_metadata:
  id: bdr:W22007
  title: བརྡ་སྤྲོད་བློ་གསལ་དགའ་སྟོན
  author: ''
  volumes:
    892be802d0644b1ca3780705b04f87be:
      image_group_id: I4731
      title: ''
      volume_number: 1
      total_pages: 236
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
